name: biopal
dependencies:
  - python=3.6
  - pip
  - GDAL
  - lxml
  - matplotlib
  - numpy
  - scipy
  - shapely
  - scikit-image
  - pandas
  - pyproj
  - setuptools
  - pip:
    - equi7grid==0.0.11
    - Pytileproj
    - progressbar2
    - namedlist
    - pyxb
    - docopt
    - pytest
