name: biopal
dependencies:
  - python>= 3.9
  - pip
  - GDAL
  - lxml
  - matplotlib
  - numpy<1.24
  - scipy
  - shapely
  - scikit-image
  - pandas
  - pyproj
  - setuptools==60.8.2
  - pip:
    - equi7grid==0.0.11
    - Pytileproj
    - progressbar2
    - namedlist
    - pyxb
    - docopt
    - pytest
    - sphinx
    - numpydoc
    - furo
    - nbsphinx
